/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_jiahaowu_balancer_task_TaskPi */

#ifndef _Included_com_jiahaowu_balancer_task_TaskPi
#define _Included_com_jiahaowu_balancer_task_TaskPi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiahaowu_balancer_task_TaskPi
 * Method:    Monte
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiahaowu_balancer_task_TaskPi_Monte
  (JNIEnv *, jobject, jint, jint);


unsigned long long rdtsc();

#ifdef __cplusplus
}
#endif
#endif
