#!/bin/bash

./cleanme
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
   gcc -fopenmp -o benchmark.exe benchmark.c -lm
elif [[ "$unamestr" == 'Darwin' ]]; then
   gcc-6 -fopenmp -o benchmark.exe benchmark.c -lm
fi
 