#!/bin/bash

./cleanme
unamestr=`uname`

if [[ "$unamestr" == 'Linux' ]]; then
   gcc -fopenmp -o sgefa_openmp.exe sgefa_openmp.c -lm
elif [[ "$unamestr" == 'Darwin' ]]; then
   gcc-6 -fopenmp -o sgefa_openmp.exe sgefa_openmp.c -lm
fi
 
